### ISSUE TITLE
How can I use pySBOL on Linux ?

### ISSUE THREAD

**Issue by Shaofanl** [bbartley/pySBOL#4]
I cannot install pySBOL on Linux. Is there anyway that I can use pySBOL on Linux-like platform ?

**Comment by jefdaj** [comment]
What commands did you try and what error message did you get?

**Comment by Shaofanl** [comment]
I made some changes on setup.py and can install pySBOL. I also create a [pull request](https://github.com/SynBioDex/pySBOL/pull/5)
But I cannot import sbol, it shows:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "build/bdist.cygwin-2.0.4-x86_64/egg/sbol/**init**.py", line 3, in <module>
>   File "build/bdist.cygwin-2.0.4-x86_64/egg/sbol/sbol.py", line 17, in <module>
> ImportError: No module named libsbol

**Comment by jefdaj** [comment]
Ah I see. I haven't worked on this in a couple years and looks like they're changing around the install code recently. Hopefully not dropping linux support! I should pass this off to @bbartley.

**Comment by bbartley** [comment]
Hi,

You are receiving that error because pySBOL depends on the C library, libSBOL, and it can't find the dependency.  Unfortunately at this time pySBOL is only distributed with precompiled binaries for Windows and MacOSX.  However, I'd be happy to work with you to get it working on Linux.  There are two options to proceed: 
1.  Build libSBOL on Linux yourself and copy the binary into the pySBOL project manually.  Comprehensive documentation and build instructions for libSBOL can be found here: https://github.com/SynBioDex/libSBOLc.   I can help if you have questions
2.  Wait for me to add Linux support.  I can probably borrow somebody else's Linux machine, build the binaries, and update the Git repository.  However, it won't happen fast.  The next two weeks are crazy, but after that things relax.

Regards
Bryan

**Comment by Shaofanl** [comment]
Hi bbartley,

It's great to know that we still get hopes to use pySBOL on Linux-like system. 
I tried to compile (using g++) on my cygwin (A linux-like simulator on Windows). And I got a file call `cygsbol.dll`. But it doesn't work when I import it, it says:
`ImportError: dynamic module does not define init function (initcygsbol)`
I searched for this problem and found that there is something missing in the C file that is used to generated API for Python. Did I compile in a wrong way or what was I missing?

BTW, when pySBOL will support SBOL 2.0.0 ?

Regards
Van
